/**
 * TypeScript types mirroring the AgentTown backend models.
 *
 * These interfaces match the JSON shapes sent over the WebSocket
 * from agenttown/server.py and the Pydantic models in
 * agenttown/world/models.py, agenttown/world/events.py, etc.
 */

// ---------------------------------------------------------------------------
// Entity states (mirrors agenttown.world.models.EntityState)
// ---------------------------------------------------------------------------

export type EntityState =
  | 'default'
  | 'locked'
  | 'unlocked'
  | 'open'
  | 'closed'
  | 'hidden'
  | 'solved'
  | 'activated';

// ---------------------------------------------------------------------------
// Core world models
// ---------------------------------------------------------------------------

/** Base world entity -- anything that exists in a room. */
export interface Entity {
  id: string;
  name: string;
  description: string;
  state: EntityState;
  portable: boolean;
  usable_on: string[];
  properties: Record<string, unknown>;
}

/** An entity that can be picked up and carried (portable=true). */
export type Item = Entity;

/** Connects two rooms. May be locked. */
export interface Door {
  id: string;
  name: string;
  description: string;
  state: EntityState;
  portable: boolean;
  usable_on: string[];
  properties: Record<string, unknown>;
  room_a: string;
  room_b: string;
  locked: boolean;
  key_id: string | null;
}

/** A location in the world containing entities. */
export interface Room {
  id: string;
  name: string;
  description: string;
  /** Map of entity_id -> Entity */
  entities: Record<string, Entity>;
  /** Map of direction -> door_id */
  doors: Record<string, string>;
}

/** The world-facing state of an agent. */
export interface AgentState {
  id: string;
  name: string;
  description: string;
  room_id: string;
  inventory: Item[];
  goal: string;
}

/** Complete snapshot of the world at a point in time. */
export interface WorldState {
  rooms: Record<string, Room>;
  agents: Record<string, AgentState>;
  doors: Record<string, Door>;
  tick: number;
  finished: boolean;
  finish_reason: string;
}

// ---------------------------------------------------------------------------
// Escape chain
// ---------------------------------------------------------------------------

export type EscapeChainStatus = 'pending' | 'solved' | 'active';

export interface EscapeChainStep {
  step: number;
  action: string;
  target: string;
  entity_id: string;
  room: string;
  room_id: string;
  description: string;
  status: EscapeChainStatus;
  check_type: string;
  /** Set when the step is solved -- which agent solved it */
  solved_by?: string;
  /** Set when the step is solved -- at which tick */
  solved_at?: number;
}

// ---------------------------------------------------------------------------
// Events (from a tick broadcast)
// ---------------------------------------------------------------------------

/** A simplified event as sent in the "tick" WS message. */
export interface TickEvent {
  type: string; // "move", "pick_up", "use", "talk", "examine", "fail", "state_change"
  description: string;
  room: string;
}

// ---------------------------------------------------------------------------
// Narrative
// ---------------------------------------------------------------------------

/** A narrative entry generated by the narrator for one tick. */
export interface NarrativeEntry {
  tick: number;
  text: string;
  events: TickEvent[];
  timestamp: number; // client-side timestamp for ordering
}

// ---------------------------------------------------------------------------
// Token usage (optional, for dev/debug display)
// ---------------------------------------------------------------------------

export interface TokenUsage {
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
}

// ---------------------------------------------------------------------------
// WebSocket message types from the server
// ---------------------------------------------------------------------------

/** Initial or reset full-state snapshot */
export interface SnapshotMessage {
  type: 'snapshot';
  tick: number;
  paused: boolean;
  world_state: WorldState;
  escape_chain?: EscapeChainStep[];
}

/** Per-tick update with events, narrative, and new world state */
export interface TickMessage {
  type: 'tick';
  tick: number;
  events: TickEvent[];
  narrative: string;
  token_usage: TokenUsage;
  token_profile: Record<string, unknown>;
  world_state: WorldState;
  escape_chain: EscapeChainStep[];
}

/** Agents are thinking / processing */
export interface ProcessingMessage {
  type: 'processing';
  tick: number;
  step: string;
  message: string;
  agents?: Record<string, string>;
}

/** Game finished */
export interface FinishedMessage {
  type: 'finished';
  reason: string;
  narrative: string;
}

/** Game already finished (idle reminder) */
export interface FinishedIdleMessage {
  type: 'finished_idle';
  tick: number;
}

/** Game paused */
export interface PausedMessage {
  type: 'paused';
  tick: number;
}

/** Union of all possible server messages */
export type ServerMessage =
  | SnapshotMessage
  | TickMessage
  | ProcessingMessage
  | FinishedMessage
  | FinishedIdleMessage
  | PausedMessage;

// ---------------------------------------------------------------------------
// Connection status
// ---------------------------------------------------------------------------

export type ConnectionStatus = 'disconnected' | 'connecting' | 'connected' | 'error';
